config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :fake_apis
  root to: "fake_apis#index"
  match "*path", to: "fake_apis#fake_api", via: :all
end

app/models/api.rb
class Api < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fake_api.rb
class FakeApi < ApplicationRecord
	belongs_to :user, dependent: :destroy, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :fake_api, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/fake_apis_controller.rb
class FakeApisController < ApplicationController
  before_action :set_fake_api, only: [:show, :edit, :update, :destroy]

  # GET /fake_apis
  # GET /fake_apis.json
  def index
    if user_signed_in?
      @fake_apis = FakeApi.where(user_id: current_user.id) || []
    else
      @fake_apis = FakeApi.all
    end
  end

  # GET /fake_apis/1
  # GET /fake_apis/1.json
  def show
  end

  # GET /fake_apis/new
  def new
    @fake_api = FakeApi.new
  end

  # GET /fake_apis/1/edit
  def edit
  end

  # POST /fake_apis
  # POST /fake_apis.json
  def create
    @fake_api = FakeApi.new(fake_api_params)
    if user_signed_in?
      @fake_api.user = current_user
    end
    respond_to do |format|
      if @fake_api.save
        format.html { redirect_to @fake_api, notice: 'Fake api was successfully created.' }
        format.json { render :show, status: :created, location: @fake_api }
      else
        format.html { render :new }
        format.json { render json: @fake_api.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fake_apis/1
  # PATCH/PUT /fake_apis/1.json
  def update
    respond_to do |format|
      if @fake_api.update(fake_api_params)
        format.html { redirect_to @fake_api, notice: 'Fake api was successfully updated.' }
        format.json { render :show, status: :ok, location: @fake_api }
      else
        format.html { render :edit }
        format.json { render json: @fake_api.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fake_apis/1
  # DELETE /fake_apis/1.json
  def destroy
    @fake_api.destroy
    respond_to do |format|
      format.html { redirect_to fake_apis_url, notice: 'Fake api was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fake_api
    verb = request.request_method
    @api = FakeApi.find_by(method: verb.downcase, uri: params["path"])
    render json: @api.response
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fake_api
      @fake_api = FakeApi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fake_api_params
      prefix = current_user.try(:name) || "fake"
      params["fake_api"]["uri"] = File.join(prefix, params["fake_api"]["uri"]).sub(/^\//, '')
      params.require(:fake_api).permit(:method, :uri, :response)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fake_apis_helper.rb
module FakeApisHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/apis/_form.html.erb
<%= form_with(model: api, local: true) do |form| %>
  <% if api.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(api.errors.count, "error") %> prohibited this api from being saved:</h2>

      <ul>
      <% api.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :action %>
    <%= form.text_field :action, id: :api_action %>
  </div>

  <div class="field">
    <%= form.label :uri %>
    <%= form.text_field :uri, id: :api_uri %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status, id: :api_status %>
  </div>

  <div class="field">
    <%= form.label :response %>
    <%= form.text_field :response, id: :api_response %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apis/edit.html.erb
<h1>Editing Api</h1>

<%= render 'form', api: @api %>

<%= link_to 'Show', @api %> |
<%= link_to 'Back', apis_path %>

app/views/apis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apis</h1>

<table>
  <thead>
    <tr>
      <th>Action</th>
      <th>Uri</th>
      <th>Status</th>
      <th>Response</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apis.each do |api| %>
      <tr>
        <td><%= api.action %></td>
        <td><%= api.uri %></td>
        <td><%= api.status %></td>
        <td><%= api.response %></td>
        <td><%= link_to 'Show', api %></td>
        <td><%= link_to 'Edit', edit_api_path(api) %></td>
        <td><%= link_to 'Destroy', api, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Api', new_api_path %>

app/views/apis/new.html.erb
<h1>New Api</h1>

<%= render 'form', api: @api %>

<%= link_to 'Back', apis_path %>

app/views/apis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Action:</strong>
  <%= @api.action %>
</p>

<p>
  <strong>Uri:</strong>
  <%= @api.uri %>
</p>

<p>
  <strong>Status:</strong>
  <%= @api.status %>
</p>

<p>
  <strong>Response:</strong>
  <%= @api.response %>
</p>

<%= link_to 'Edit', edit_api_path(@api) %> |
<%= link_to 'Back', apis_path %>

app/views/fake_apis/_form.html.erb
<%= form_for @fake_api, :html => { :class => "form-horizontal fake_api" } do |f| %>

  <% if @fake_api.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@fake_api.errors.count, "error") %> prohibited this fake_api from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @fake_api.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :method, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :method, :class => 'form-control' %>
    </div>
    <%=f.error_span(:method) %>
  </div>
  <div class="form-group">
    <%= f.label :uri, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :uri, :class => 'form-control' %>
    </div>
    <%=f.error_span(:uri) %>
  </div>
  <div class="form-group">
    <%= f.label :response, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :response, :class => 'form-control' %>
    </div>
    <%=f.error_span(:response) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                fake_apis_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/fake_apis/edit.html.erb
<%- model_class = FakeApi -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fake_apis/index.html.erb
<%- model_class = FakeApi -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:method) %></th>
      <th><%= model_class.human_attribute_name(:uri) %></th>
      <th><%= model_class.human_attribute_name(:response) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @fake_apis.each do |fake_api| %>
      <tr>
        <td><%= link_to fake_api.id, fake_api_path(fake_api) %></td>
        <td><%= fake_api.method %></td>
        <td><%= fake_api.uri %></td>
        <td><%= fake_api.response %></td>
        <td><%=l fake_api.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      fake_api_path(fake_api), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_fake_api_path(fake_api), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      fake_api_path(fake_api),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_fake_api_path,
            :class => 'btn btn-primary' %>

app/views/fake_apis/new.html.erb
<%- model_class = FakeApi -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fake_apis/show.html.erb
<%- model_class = FakeApi -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:method) %>:</strong></dt>
  <dd><%= @fake_api.method %></dd>
  <dt><strong><%= model_class.human_attribute_name(:uri) %>:</strong></dt>
  <dd><%= @fake_api.uri %></dd>
  <dt><strong><%= model_class.human_attribute_name(:response) %>:</strong></dt>
  <dd><%= @fake_api.response %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              fake_apis_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_fake_api_path(@fake_api), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              fake_api_path(@fake_api),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FakeServer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="hmenu">
      <%= render 'devise/menu/registration_items' %>
      <%= render 'devise/menu/login_items' %>
    </ul>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>